### ISSUE TITLE
feature error

### ISSUE THREAD

**Issue by nanife** [adobe-type-tools/Adobe-KR#1]
<img width="748" alt="featureerror" src="https://user-images.githubusercontent.com/10296213/45507268-8b1dd680-b7cc-11e8-9954-4988fab34459.png">

**Comment by kenlunde** [comment]
@nanife Thank you for reporting this. This particular 'dlig' GSUB feature bug was inherited from [_Source Han Serif_](https://github.com/adobe-fonts/source-han-serif/), which inherited it from [_Source Han Sans_](https://github.com/adobe-fonts/source-han-sans/). The original substitution, using Unicode-based working glyph names, is below:

`substitute uni0063 uni006D uni0022 by uni33A0;`

It should have been as follows:

`substitute uni0063 uni006D uni0032 by uni33A0;`

I will update the two fonts in the [latest release](https://github.com/adobe-type-tools/Adobe-KR/releases/latest/) in a day or two.

**Comment by kenlunde** [comment]
Now fixed in the Version 1.005 fonts that are downloadable in the [latest release](https://github.com/adobe-type-tools/Adobe-KR/releases/latest/).
