### ISSUE TITLE
unusual glyph name

### ISSUE THREAD

**Issue by schriftgestalt** [adobe-type-tools/Adobe-KR#2]
the file Adobe-KR-9_ordering.txt contains this line:
```
22461	Hanja	ExtGr307	u01200
```
cid22461 is not actually encoded but the glyph name looks like it has an unicode. I doubt that you mean `ETHIOPIC SYLLABLE HA`.

**Comment by kenlunde** [comment]
Completely intentional. Read [this](https://github.com/adobe-type-tools/Adobe-KR#special-notes-4).

**Comment by schriftgestalt** [comment]
I didn’t see that. Sorry. But maybe call it `UTC01200` for now?

**Comment by kenlunde** [comment]
I prefer to leave the _working_ glyph name as-is until Extension G becomes stable, at which point its glyph name will reflect its Plane 3 code point. Feel free to change the glyph name to something else for anything that is a derivative work.
